### ISSUE TITLE
[3.0.2] Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by boris-petrov** [collab-project/videojs-wavesurfer#101]
[This line](https://github.com/collab-project/videojs-wavesurfer/blob/3.0.2/src/js/middleware.js#L8) is always called by `video.js` when playing something. However, if `videojs-wavesurfer` hasn't been configured in the options (but has been loaded as a plugin), `this.player.wavesurfer().surfer` is `undefined` and that line blows up. Or am I missing something?

**Comment by thijstriemstra** [comment]
thanks for the report @boris-petrov. I will add an example/test with multiple (non-)videojs-wavesurfer instances to verify all works properly and fix that issue.

**Comment by thijstriemstra** [comment]
Related to https://github.com/videojs/video.js/issues/6311

**Comment by thijstriemstra** [comment]
PR #102 should fix it, can you give it a try @boris-petrov?

![Screenshot from 2020-05-13 15-01-34](https://user-images.githubusercontent.com/305679/81816803-2203de80-952c-11ea-901f-9d74f7c09a16.png)

**Comment by boris-petrov** [comment]
@thijstriemstra - thank you for the great support! This PR seems to fix the issue, yes, thanks!

**Comment by thijstriemstra** [comment]
Released as v3.0.3.
