### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined  

### ISSUE THREAD

**Issue by ssp4all** [collab-project/videojs-wavesurfer#106]
## Description
On hitting the play button on https://collab-project.github.io/videojs-wavesurfer/demo/live.html 
it is showing below error on console.

`
Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
    at MicrophonePlugin.fireEvent (observer.js:125)
    at MicrophonePlugin.deviceError (microphone.js:348)
    at microphone.js:153
`

## Steps to reproduce
Go to https://collab-project.github.io/videojs-wavesurfer/demo/live.html then hit the play button,  then open console on the browser. 

### Expected
- No error 
- Download recorded audio.

### Actual
Not able to download audio also error was thrown in the console

### Error output
`
Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
    at MicrophonePlugin.fireEvent (observer.js:125)
    at MicrophonePlugin.deviceError (microphone.js:348)
    at microphone.js:153
`
## Versions
Make sure to include the following versions:
### videojs/wavesurfer
what version of video.js, videojs-wavesurfer and wavesurfer.js does this occur with?
- video.js 7.7.6 
- videojs-wavesurfer 3.2.0 
- wavesurfer.js 4.0.0

**Comment by thijstriemstra** [comment]
yea it's an issue with wavesurfer.js 4.0.0. Use wavesurfer.js 3.3.3 for now. See https://github.com/katspaugh/wavesurfer.js/issues/1975

**Comment by ssp4all** [comment]
Hey, @thijstriemstra thanks for a quick response.

**Comment by thijstriemstra** [comment]
I'll reopen this and close it once a new wavesurfer.js is released.

**Comment by thijstriemstra** [comment]
Use wavesurfer.js v4.0.1 or newer instead.
