### ISSUE TITLE
Angular 9 how to run without webpack

### ISSUE THREAD

**Issue by dineshmaths1** [collab-project/videojs-wavesurfer#108]
i want to record audio only How to use with out webpack ?

**Comment by thijstriemstra** [comment]
Try https://github.com/videojs/video.js/blob/main/docs/guides/angular.md and enable the videojs-wavesurfer plugin.

**Comment by dineshmaths1** [comment]
> Try https://github.com/videojs/video.js/blob/main/docs/guides/angular.md and enable the videojs-wavesurfer plugin.

I want to record my audio

**Comment by thijstriemstra** [comment]
@dineshmaths1 that's a different project, see https://github.com/collab-project/videojs-record.
