### ISSUE TITLE
angular 9 video record is not supporting

### ISSUE THREAD

**Issue by dineshmaths1** [collab-project/videojs-wavesurfer#110]
am getting this error

import videojs from 'video.js';
import * as RecordRTC from 'recordrtc';
import * as WaveSurfer from 'wavesurfer.js';
import * as MicrophonePlugin from 'wavesurfer.js/dist/plugin/wavesurfer.microphone.js';
WaveSurfer.microphone = MicrophonePlugin;
import * as Record from 'videojs-record/dist/videojs.record.js';

WARNING in ./node_modules/RecordRTC/RecordRTC.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/apple/Documents/audio/node_modules/RecordRTC/RecordRTC.js
    Used by 1 module(s), i. e.
    /Users/apple/Documents/audio/node_modules/videojs-record/dist/videojs.record.js
* /Users/apple/Documents/audio/node_modules/recordrtc/RecordRTC.js
    Used by 2 module(s), i. e.
    /Users/apple/Documents/audio/node_modules/@ngtools/webpack/src/index.js!/Users/apple/Documents/audio/src/app/app.component.ts

ERROR in ./node_modules/videojs-record/dist/videojs.record.js
Module not found: Error: Can't resolve 'videojs' in '/Users/apple/Documents/audio/node_modules/videojs-record/dist'

 "dependencies": {
    "@angular/animations": "~9.1.1",
    "@angular/common": "~9.1.1",
    "@angular/compiler": "~9.1.1",
    "@angular/core": "~9.1.1",
    "@angular/forms": "~9.1.1",
    "@angular/platform-browser": "~9.1.1",
    "@angular/platform-browser-dynamic": "~9.1.1",
    "@angular/router": "~9.1.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "videojs-record": "^4.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }

**Comment by thijstriemstra** [comment]
You reported this issue in the wrong repository. You already opened a new one there (https://github.com/collab-project/videojs-record/issues/493) but could've closed this one as well, which I will do now.
