### ISSUE TITLE
Error: plugin "wavesurfer" does not exist

### ISSUE THREAD

**Issue by dhavalsoni2001** [collab-project/videojs-wavesurfer#113]
## Description
I am currently trying to integrate the above plugin on https://github.com/react-boilerplate/react-boilerplate-cra-template - boilerplate.  But I am getting the error like `Error: plugin "wavesurfer" does not exist`.

## Steps to reproduce
Here is the sample repo to reproduce this issue : https://github.com/dhavalsoni2001/videojs-react-boilerplate-cra-template

### Expected

I should not get this error and plugins should load normally. 

### Actual
Please describe what actually happened.
Getting error like `Error: plugin "wavesurfer" does not exist`

## Versions
Make sure to include the following versions:
### videojs/wavesurfer
what version of video.js, videojs-wavesurfer and wavesurfer.js does this occur with?

I am using latest version of video.js, videojs-wavesurfer and wavesurfer.js
### Browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
I am facing issue on google chrome in both cognito and normal mode.
### OSes
what platforms (operating systems and devices) are affected?
I am using MacOS.

**Comment by thijstriemstra** [comment]
There is this guide for React: https://collab-project.github.io/videojs-wavesurfer/#/react

Any other usage of React, I can't help you with that.

**Comment by dhavalsoni2001** [comment]
I had followed that guide and still, it wasn't working that's why I have raised the ticket for the same.

**Comment by thijstriemstra** [comment]
@dhavalsoni2001 the guide was updated yesterday (along with a new 3.3.0 release), did you use the new guide?

**Comment by thijstriemstra** [comment]
you should first follow the guide step for step, see if it works (absolutely should), and then start integrating it into a different app. If it doesn't work in the other app, you can start comparing the differences and see where the issue is.

**Comment by thijstriemstra** [comment]
I followed the guide on macOS Catalina step-by-step just now, and it worked fine:

<img width="428" alt="Screenshot 2020-08-11 at 14 02 27" src="https://user-images.githubusercontent.com/305679/89895014-63636300-dbdb-11ea-80cb-576511626794.png">

**Comment by dhavalsoni2001** [comment]
Hey, @thijstriemstra  Thanks for the response.  I have tried it today and still facing same issue, I am currently using  3.3.0 version of the plugin.

I am using https://github.com/react-boilerplate/react-boilerplate-cra-template boilerplate for the project.

Here is the project repo to reproduce the issue.  https://github.com/dhavalsoni2001/video-js-wavesurfer-plugin-demo
![Screenshot 2020-08-11 at 7 39 19 PM](https://user-images.githubusercontent.com/11704436/89907527-69bd0380-dc0a-11ea-8f56-63bb203858b9.png)

**Node Version :** 
12.17.0

**OS:**
macOS Catalina

**Comment by thijstriemstra** [comment]
Can you reproduce it using the videojs-wavesurfer react guide? Any other project, I can't help you with.

**Comment by hassaans** [comment]
@dhavalsoni2001 were you able to fix the error?

**Comment by nickmerwin** [comment]
@hassaans can you please elaborate on your workaround?

I'm using esbuild and having the same issue where the plugin isn't being registered.
