### ISSUE TITLE
Pre-render/decode waveform

### ISSUE THREAD

**Issue by naurelijs** [collab-project/videojs-wavesurfer#12]
Hello!

Thank you for your work, i love it. 

Are there are any possibilities to add custom waveform image or something else before pre-render/pre-decode and allow play audio? 

Thanks!

**Comment by thijstriemstra** [comment]
I'll have to look into it.

**Comment by thijstriemstra** [comment]
@naurelijs you can add a custom 'poster' image behind the player, it's a standard video.js feature. For example:

```javascript
var player = videojs("myAudio",
{
    controls: true,
    autoplay: true,
    loop: false,
    width: 600,
    height: 300,
    poster: "https://upload.wikimedia.org/wikipedia/commons/5/58/Sunset_2007-1.jpg",
    plugins: {
        wavesurfer: {
            src: "media/heres_johnny.wav",
            msDisplayMax: 10,
            waveColor: "grey",
            progressColor: "black",
            cursorColor: "black",
            hideScrollbar: true
        }
    }
});
```
This renders something like:

<img width="613" alt="screen shot 2015-12-21 at 20 12 08" src="https://cloud.githubusercontent.com/assets/305679/11939013/29221334-a81f-11e5-9ae3-7a6b3f4dde51.png">

You could hide it again once the video.js player completed loading.
