### ISSUE TITLE
redrawWaveform Breaks Regions and is Possibly Not Needed

### ISSUE THREAD

**Issue by DrLongGhost** [collab-project/videojs-wavesurfer#132]
## Description
When video.js has fluid set to "true", the redrawWaveform() method is called every time the page is resized.

This method destroys Wavesurfer then tries to reinstantiate it and restore playback position and anything else that was affected. This behavior fails to take into account the regions plugin. Thus, Wavesurfer could have regions showing which are suddenly made to disappear simply because the end user resized the window. Presumably, numerous other plugins and end user customizations might also be affected in a similar manner.

This behavior is particularly concerning in my opinion for two reasons:
- This is not regular Wavesurfer behavior and instead is introduced by this plugin. Thus, you have a case where Wavesurfer behaves differently in a resize when this plugin is installed than it would when running without the plugin. I don't think it is intuitive to expect Video.js config options to push new behavior into Wavesurfer itself.
- I don't even think the resize behavior is needed. When the redrawWaveform() method is removed from the plugin and you resize the page, both Video.js and Wavesurfer correctly adjust themselves to the new width and the "fluid" layout still works. So whatever it is that redrawWaveform() is doing or why it was added, I'm not sure that it is even needed. It might be doing more harm than good.

For my purposes I did discover that, after instantiation, I can disable the problematic behavior with this snippet:

`this.player.wavesurfer().redrawWaveform = () => { };`

## Steps to reproduce

1. Install Wavesurfer, Video.js, the plugin and the regions plugin.
2. Use the plugin to highlight a region on the waveform
3. Resize the window

### Expected
I would expect to see the region remain highlighted

### Actual
The highlighted region disappears.

### Error output
None

## Versions

    "video.js": "^7.10.2",
    "videojs-wavesurfer": "^3.5.0",
    "wavesurfer.js": "^4.4.0"

### Browsers
Presumably all. Tested on Chrome on Mac.
### OSes
Presumably all. Tested on Chrome on Mac.

**Comment by thijstriemstra** [comment]
> I don't even think the resize behavior is needed. When the redrawWaveform() method is removed from the plugin and you resize the page, both Video.js and Wavesurfer correctly adjust themselves to the new width and the "fluid" layout still works. So whatever it is that redrawWaveform() is doing or why it was added, I'm not sure that it is even needed. It might be doing more harm than good.

I agree.

It's probably the css that does a good enough job:

```css
/* Handle responsive / fluid view.
--------------------------------------------------------------------------------
*/
.vjs-wavesurfer.vjs-fluid wave.vjs-wavedisplay {
    top: 0;
    position: absolute!important;
    width: 100%;
    min-width: 100%;
    max-width: 100%;
    height: 100%;
}
```

I will get rid of the resize handlers.
