### ISSUE TITLE
Toggle Waveform

### ISSUE THREAD

**Issue by mikemorton** [collab-project/videojs-wavesurfer#14]
Forgive me if this is an obvious question, but I wonder if it is possible for me to programatically toggle the waveform while video/audio is playing?  I'd like to allow users to switch between waveform view and the regular content of the video.

**Comment by thijstriemstra** [comment]
This is related to https://github.com/collab-project/videojs-wavesurfer/issues/8#issuecomment-135465859. There you'll find an example that shows the video underneath the waveform. You could then use css to hide the waveform or video. It's hacky though but worth a try..
