### ISSUE TITLE
How to compile to ES5

### ISSUE THREAD

**Issue by samueleastdev** [collab-project/videojs-wavesurfer#140]
i would like to use this plugin but I cant seem to get it to compile to es5.

Could you help me with this or point me in the right direction.

I have try adjusting the .babelrc file with the following as per their docs.

~~~
{
  "presets": ["@babel/preset-env"],
  "plugins": ["add-module-exports"],
  "env": {
      "test": {
        "plugins": [
          ["istanbul", {
            "exclude": [
              "test/**/*.spec.js"
          ]
        }]
      ]
    }
  }
}
~~~

In their docs they say to leave it blank to compile to ES5 

https://babeljs.io/docs/en/babel-preset-env

**No targets
Since one of the original goals of preset-env was to help users easily transition from using preset-latest, it behaves similarly when no targets are specified: preset-env will transform all ES2015-ES2020 code to be ES5 compatible.**

After updating that file and running.
~~~
npm run build
~~~

It is still compiling to ES6 if you look at the js file. 
~~~
(() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({
~~~

When using grunt with this it fails with a punctuation error (() =>

Not sure what I am doing wrong?

Thanks

**Comment by thijstriemstra** [comment]
@samueleastdev you need to skip webpack and only use the `babel` command if you don't want those webpack statements. Can you follow steps in this video: https://www.youtube.com/watch?v=z_XkUSaQ5UY

**Comment by thijstriemstra** [comment]
did you manage to get it to work @samueleastdev?
