### ISSUE TITLE
Wavesurfer.js region events

### ISSUE THREAD

**Issue by DManujaya** [collab-project/videojs-wavesurfer#147]
I am trying to extend the region and timeline implementation from the example in the documentation [linked here](https://collab-project.github.io/videojs-wavesurfer/demo/plugin.html). I want to run a function on "region-click" or on "region-play" but to no avail. Is there a specific way to do this?
The Wavesurfer region events can be found [here](https://wavesurfer-js.org/plugins/regions.html)

**Comment by DManujaya** [comment]
![image](https://user-images.githubusercontent.com/88760921/129553602-04e9ba3a-53d9-4a98-b5fe-004e4f02f87a.png)
This is how I tried on Angular 9

**Comment by thijstriemstra** [comment]
@DManujaya take a look at https://collab-project.github.io/videojs-wavesurfer/#/methods?id=wavesurferjs

And try:

```javascript
player.wavesurfer().surfer.on('region-click', function(region, e) {
  console.log("YES!");
});
```

I also updated the plugin example to include this change.

**Comment by DManujaya** [comment]
Yup that works like a charm. Thanks a lot
