### ISSUE TITLE
getPeaks() returns an empty array

### ISSUE THREAD

**Issue by DManujaya** [collab-project/videojs-wavesurfer#149]
I'm trying to get the peak data of a WAV file so that I can cluster the silences in the audio but the `getPeaks()` method returns an empty array. 
Any help would be really appreciated.

This is what I have tried so far:

```
this.player.on("waveReady", (event) => {
      var length = this.player.wavesurfer().surfer.getDuration();
      var start = 0;
      var end = length;
      console.log(
        this.player.wavesurfer().surfer.backend.getPeaks(length, start, end)
      );
    });
```

**Comment by thijstriemstra** [comment]
you should include the videojs(-record) configuration and version nrs. It's part of ticket guidelines!!

**Comment by DManujaya** [comment]
Sorry about that!
react: 17.0.2",
videojs-wavesurfer: 3.8.0

**Comment by DManujaya** [comment]
@thijstriemstra Is there any update?

**Comment by thijstriemstra** [comment]
im on a holiday. do you see any updates? you know it's very rude to demand an answer from me?

**Comment by DManujaya** [comment]
@thijstriemstra Really sorry about that. Didn't mean to come off as aggressive. Enjoy your holiday. 
Once again I apologize

**Comment by thijstriemstra** [comment]
You shouldn't check it in the `waveReady` event. Trying your example and pasting this in the console:

```
var length = player.wavesurfer().surfer.getDuration();
      var start = 0;
      var end = length;
      console.log(
        player.wavesurfer().surfer.backend.getPeaks(length, start, end)
      );
```

And I see the peaks data:

<img width="384" alt="Screenshot 2021-11-28 at 00 28 18" src="https://user-images.githubusercontent.com/305679/143723293-5765aa0f-a99a-4707-a8ff-d8aeefaba637.png">
