### ISSUE TITLE
autoplay:false but safari recognize it as autoplay

### ISSUE THREAD

**Issue by OishiNanano** [collab-project/videojs-wavesurfer#150]
Hi, we enjoy your project :)

We disable the autoplay setting, but we can't play sound on safari and firefox.
Only when we allow autoplay in browser setting, we can play.

## Versions
macOS big sur: 11.2.3
safari: 14.0.3
firefox: 92.0.1
videojs-wavesurfer: 3.7.0
Video.js: 7.11.8
wavesurfer.js: 5.0.1

## Steps to reproduce
Our settings is below.
```
    var options = {
        controls: true,
        autoplay: false,
        loop: false,
        muted: false,
        fluid: false,
        preload: 'auto',
        bigPlayButton: false,
        width: 575,
        height: 300,
        plugins: {
            wavesurfer: {
                backend: 'MediaElementWebAudio',
                displayMilliseconds: false,
                cursorColor: '#555555',
                splitChannels: true,
                normalize: true,
                interact: true,
                hideScrollbar: true,
                backgroundColor: '#FFF',
                responsive: true,
                splitChannelsOptions: {
                    overlay: false,
                    relativeNormalization: true,
                    channelColors: {
                        0: {
                            progressColor: '#4353FF',
                            waveColor: '#D9DCFF'
                        },
                        1: {
                            progressColor: '#4E8485',
                            waveColor: '#B2D9AC'
                        }
                    }
                },
            }
        },
        controlBar: {
            fullscreenToggle: false
        },
        language: 'ja'
    };
```

Thanks.

**Comment by thijstriemstra** [comment]
I tested with Firefox 94.0.2 on macOS 12.0.1 with your settings and it worked fine on http://localhost:8080/examples/index.html

Safari Tech Preview 135 (Safari 15.4, WebKit 17613.1.7.3) also worked fine.

I didn't work properly with latest stable Safari 15.1 (17612.2.9.1.20) desktop.

Haven't tested with iOS.

**Comment by OishiNanano** [comment]
I apologise for the delay in replying to you.

I updated Firefox and tested with Firefox 96.0.2 again. It worked fine!
In my environment, in the case which prohibits autoplay, default volume is muted. So, I think I misunderstood it can't play.
I'm sorry.

And it worked fine on future version of safari is good news! 
Thank you for your investigation.
