### ISSUE TITLE
Using zoom on videojs-wavesurfer

### ISSUE THREAD

**Issue by shallfer7** [collab-project/videojs-wavesurfer#153]
Hi

Is there any way to implement zoom on videojs-wavesurfer ? Something like [this](https://wavesurfer-js.org/example/zoom/index.html), but on the waveform of videojs

Thank you

**Comment by thijstriemstra** [comment]
Yes, you can set the zoom level on wavesurfer.js like this (based on the example you linked):

```js
document.querySelector('#slider').oninput = function () {
    player.wavesurfer().surfer.zoom(Number(this.value));
};
```
