### ISSUE TITLE
How to use inside a sophisticated react-js app

### ISSUE THREAD

**Issue by Megidd** [collab-project/videojs-wavesurfer#154]
## Description
I'm trying to use `videojs-wavesurfer` inside a sophisticated react-js app. I have studied and followed these docs:

https://collab-project.github.io/videojs-wavesurfer/#/usage
https://collab-project.github.io/videojs-wavesurfer/#/react

But I have a hard time integrating `videojs-wavesurfer` into current code. I'm seeking help here. Can anybody help us figure out how `videojs-wavesurfer`  should be used?
## Steps to reproduce
The exact steps taken to do the integration are available here: https://github.com/mediacms-io/mediacms/pull/403
### Expected
I expected to see the ` videojs-wavesurfer` effect while playing audio.
### Actual
Unfortunately, ` videojs-wavesurfer` has no effect.
## Versions
```
"videojs-wavesurfer": "^3.8.0"
```
```
video.js": {
      "version": "7.12.3",
```
```
"wavesurfer.js": {
      "version": "5.2.0",
```
### Browsers
Any browser.
### OSes
Linux.

**Comment by thijstriemstra** [comment]
> Unfortunately, videojs-wavesurfer has no effect.

What kind of error messages etc are you seeing?

**Comment by Megidd** [comment]
Thanks @thijstriemstra :smiley: The strange thing is that no error message is received. Nothing.

Everything seems to be fine, but `videojs-wavesurfer` is apparently ignored altogether.

**Comment by thijstriemstra** [comment]
Hmm. Without any errors it's hard to say what's wrong.. Maybe you should try integrating video.js only first: https://docs.videojs.com/tutorial-react.html

**Comment by Megidd** [comment]
@thijstriemstra Makes sense :) I'm going to do that.

> Hmm. Without any errors it's hard to say what's wrong.. Maybe you should try integrating video.js only first: https://docs.videojs.com/tutorial-react.html

**Comment by Megidd** [comment]
@thijstriemstra Integrating the `video.js` only first, and then adding `videojs-wavesurfer` plugin, leads to an error. I'm trying to debug it :slightly_smiling_face: 

https://github.com/mediacms-io/mediacms/pull/403#issuecomment-1029721433

**Comment by thijstriemstra** [comment]
@Megidd make sure the following code is working correctly, which prints all version numbers for the required javascript dependencies:

```js
// print version information at startup
const version_info = 'Using video.js ' + videojs.VERSION +
    ' with videojs-wavesurfer ' + videojs.getPluginVersion('wavesurfer') +
    ', wavesurfer.js ' + WaveSurfer.VERSION + ' and React ' + React.version;
videojs.log(version_info);
```

because it looks like you don't have wavesurfer.js properly included.

**Comment by Megidd** [comment]
Thanks @thijstriemstra :smile: 

For some reason, this error is thrown before I can do any logs:

> Uncaught TypeError: Cannot read properties of undefined (reading 'params')

# Simple demo

To better understand the error cause, I created this simple *demo* repository:

https://github.com/Megidd/videojs-wavesurfer-react

Based on this guide:

https://collab-project.github.io/videojs-wavesurfer/#/react

The simple *demo* code works fine:

![Screenshot_20220206_050750](https://user-images.githubusercontent.com/17475482/152664931-68cb9e3a-64fd-46ed-9a0c-ffb5332a6cbc.png)

So now, I will have to investigate further to figure out what I'm missing in the sophisticated React app...

**Comment by Megidd** [comment]
Finally, audio wave is visualized just fine by commit https://github.com/mediacms-io/mediacms/pull/403/commits/e12367edc523accf8768d28c45ae350eb97c3830

![Screenshot_20220211_193044](https://user-images.githubusercontent.com/17475482/153625803-996d13e4-ae3f-40d4-ada2-fd60c4b0e0c2.png)

# Note

The audio wave is visualized fine. However, it is not played for some reason. I guess debugging why the audio isn't played would be a whole new problem I will have to tackle. So, let's close this issue and open another one for it :smile:

**Comment by Megidd** [comment]
Here is the continuation of this problem:

https://github.com/videojs/video.js/discussions/7644

Basically, I have to register and initialize `videojs-wavesurfer` plugin alongside another *custom* videojs plugin. It's a bit tricky for me :smile:
