### ISSUE TITLE
Register manually

### ISSUE THREAD

**Issue by Megidd** [collab-project/videojs-wavesurfer#159]
## Automatic registering

`videojs-wavesurfer` plugin registers itself automatically upon proper import:

```js
import 'video.js/dist/video-js.css';
import videojs from 'video.js';

import WaveSurfer from 'wavesurfer.js';

// The videojs-wavesurfer plugin automatically registers itself after importing it:
import 'videojs-wavesurfer/dist/css/videojs.wavesurfer.css';
import Wavesurfer from 'videojs-wavesurfer/dist/videojs.wavesurfer.js';
```
## Problem

Sometimes, the exact sequence of above imports is *not* possible. For example `videojs` is already declared somewhere else inside the application and cannot be imported again.

Is there a way to register it manually? I have tried this, but it didn't work:

```js
// Apparently videojs is already imported somewhere else inside the app.
// So, it cannot be imported again.

import WaveSurfer from 'wavesurfer.js';

// The videojs-wavesurfer plugin automatically registers itself after importing it:
import 'videojs-wavesurfer/dist/css/videojs.wavesurfer.css';
import Wavesurfer from 'videojs-wavesurfer/dist/videojs.wavesurfer.js';


// ...


	/*
	 * Register videojs-wavesurfer plugin manually.
	 * Since it didn't get registered automatically upon import.
	 */

	videojs.registerPlugin('wavesurfer', Wavesurfer);

	/*
	 * Debug logs
	 */

	videojs.log(videojs.getPlugins())

	const version_info = 'Using video.js ' + videojs.VERSION +
		' with videojs-wavesurfer ' + videojs.getPluginVersion('wavesurfer') +
		', wavesurfer.js ' + WaveSurfer.VERSION;
	videojs.log(version_info);


	/* 
	 * Initialize videojs-wavesurfer plugin by calling it.
	 */

	this.player.wavesurfer(
		/* Pass wavesurfer options here */
		{
			backend: 'MediaElement',
			displayMilliseconds: true,
			debug: true,
			waveColor: '#163b5b',
			progressColor: 'black',
			cursorColor: 'black',
			hideScrollbar: true
		}
	);
```

The above code throws this error:

> Uncaught Error: Illegal plugin for "wavesurfer", must be a function, was object.

I just wanted to double-check if there is a way to register the `videojs-wavesurfer` plugin manually? Maybe it can be done by fine-tuning its source code?

**Comment by thijstriemstra** [comment]
> I just wanted to double-check if there is a way to register the videojs-wavesurfer plugin manually? 

No, there currently isn't, it's registered automatically.

> Maybe it can be done by fine-tuning its source code?

You can remove the register call and do it yourself elsewhere: https://github.com/collab-project/videojs-wavesurfer/blob/master/src/js/videojs.wavesurfer.js#L836

**Comment by Megidd** [comment]
@thijstriemstra Alright :) I'm going to try to remove the register call and do it myself. Maybe I can work around my problem by this approach.

**Comment by Micrufun** [comment]
Sorry @thijstriemstra :smile: I noticed this issue is closed. Is it implemented? I'm just curious sorry :sweat_smile:

**Comment by Megidd** [comment]
Sorry @thijstriemstra :smile: I noticed this issue is closed. Is it implemented? I'm just curious sorry :sweat_smile:
