### ISSUE TITLE
VIDEOJS: ERROR: Error: HTTP error status: 0

### ISSUE THREAD

**Issue by esukmonica** [collab-project/videojs-wavesurfer#160]
I have taken the "Wavesurfer Plugin Video Example" and change the video file to be played to:

`    // load file
    player.src({src: 'test.mp4', type: 'video/mp4'});`

When loading the page I get  "ERROR: Error: HTTP error status: 0". The video file plays, but no waveform is displayed.

Any ideas?

Thanks

[videojswavesurfer.zip](https://github.com/collab-project/videojs-wavesurfer/files/8208103/videojswavesurfer.zip)
![videojswaveform_notworking](https://user-images.githubusercontent.com/63296463/157286259-efba5088-f59b-4032-bcb7-3d706996fc27.PNG)

**Comment by thijstriemstra** [comment]
@esukmonica are you able to play the video file directly in the browser using a URL?

**Comment by esukmonica** [comment]
Yes, I can play the video in Chrome via: http://localhost/video/test.mp4

However, if I replace

`player.src({src: 'test.MP4', type: 'video/mp4'});`

with

`player.src({src: 'http://localhost/video/test.mp4', type: 'video/mp4'});`

then I still get the same error and no waveform, but now I cannot play the video neither. I do not get any of the player controls either (play, volume buttons)

`video.min.js:12 VIDEOJS: ERROR: Error: HTTP error status: 0
    at wavesurfer.js:2850:11`



![sample_with_url](https://user-images.githubusercontent.com/63296463/157412271-f94f7158-fca3-4563-b32f-6baa4f378d65.PNG)

Tests are being done with: Chrome Version 99.0.4844.51/Windows 10 Pro

Thanks

**Comment by thijstriemstra** [comment]
Can you try other browsers, e.g. firefox or edge?

**Comment by esukmonica** [comment]
Firefox: 98.0 (64-bit). Applies to both scenarios (having a video source as URL or within the page)

- Video cannot be played
- No waveform
- No video controls

EDGE: Version 99.0.1150.36 (Official build) (64-bit), behaves in the same way as chrome. if video is within page, it can be played but no waveform is displayed, if video source uses the video URL, the video cannot be played and no waveform is displayed

**Comment by thijstriemstra** [comment]
The regular example works ok: https://collab-project.github.io/videojs-wavesurfer/demo/video.html

Can you try a different video, and maybe also paste output of `ffprobe` (part of ffmpeg) for the video here.

**Comment by esukmonica** [comment]
Thanks thijstriemstra

All working now. The error was caused by opening the .html directly from disk. 

I have now opened the html via the URL and I get the waveform
