### ISSUE TITLE
Zoom method not found in player.wavesurfer().surfer

### ISSUE THREAD

**Issue by snorreks** [collab-project/videojs-wavesurfer#163]
## Description
I want to use the [zoom](https://wavesurfer-js.org/example/zoom/index.html) method from [wavesurfer.js](https://wavesurfer-js.org/docs/methods.html). But when using player.wavesurfer().surfer it  does not show the zoom method #153.

## Steps to reproduce
How I initialize the player:
```ts
import VideoJs from 'video.js';
import 'videojs-wavesurfer/dist/css/videojs.wavesurfer.css';
import 'wavesurfer.js';
import 'videojs-wavesurfer/dist/videojs.wavesurfer.js';

VideoJS(this.videoElement, {
   ...
   plugins: {
            wavesurfer: {
              backend: 'MediaElement',
              interact: false,
              displayMilliseconds: false,
              debug: false,
              waveColor: '#C6D3E9',
              progressColor: '#C6D3E9',
              cursorColor: 'rgba(0, 0, 0, 0)',
              hideScrollbar: true,
              // put waveform in separate container
              container: this.waveContainerId,
            },
   }
})
```
### Expected
Expecting to find and use the zoom method.

### Actual
player.wavesurfer().surfer outputs this:
![image](https://user-images.githubusercontent.com/36089469/163567498-5a2cba20-8240-4311-83da-98ae00222d3d.png)

## Versions
video.js: 7.19.0
videojs-wavesurfer: 3.8.0
wavesurfer.js: 6.1.0
### Browsers
Chrome
### OSes
Windows

**Comment by thijstriemstra** [comment]
I tried this is in a browser console on https://collab-project.github.io/videojs-wavesurfer/demo/index.html

And zoom etc is available:

![Capture](https://user-images.githubusercontent.com/305679/163569436-d2d002dd-6abd-4116-81b8-89b0bf10e10c.JPG)

**Comment by snorreks** [comment]
it works after all! it was hidden in prototype.
