### ISSUE TITLE
Support for wavesurfer.js 7.0 or newer

### ISSUE THREAD

**Issue by DigitLib** [collab-project/videojs-wavesurfer#172]
## Description
Online Demos on documentation don't work

## Steps to reproduce
Click on this example https://collab-project.github.io/videojs-wavesurfer/demo/texttrack.html

After looking the problem found that wavesurfer version is 7.x but it works on 6.6.0.

**Comment by thijstriemstra** [comment]
> After looking the problem found that wavesurfer version is 7.x but it works on 6.6.0.

Right. I am not interested in upgrading videojs-wavesurfer to wavesurfer.js v7.0 at this moment. If anyone wants to take a look, please do.

**Comment by thijstriemstra** [comment]
I'm releasing a videojs-wavesurfer v3.10.0 soon that will limit the supported wavesurfer.js to < 7.0.0.
