### ISSUE TITLE
BUG video.min.js:12 VIDEOJS: ERROR: TypeError: Cannot read properties of undefined (reading 'backend')

### ISSUE THREAD

**Issue by pioner-rtx** [collab-project/videojs-wavesurfer#174]
## Description
Lib is not working because instaed prop "option" you use  prop "param"

in node_modules videojs.wavesurfer.js
str 149 
Actual => var backend = this.player.wavesurfer().surfer.params.backend;
Expected => var backend = this.player.wavesurfer().surfer.options.backend;

str 571
Actual =>  this.backend = this.surfer.params.backend;
Expected => this.backend = this.surfer.options.backend;

in repo midleware
str 17  let backend = this.player.wavesurfer().surfer.params.backend;

in repo videojs.wavesurfer.js
str 138 this.backend = this.surfer.params.backend;

For reproducing https://collab-project.github.io/videojs-wavesurfer/demo/video.html

**Comment by thijstriemstra** [comment]
> Lib is not working because instaed prop "option" you use prop "param"

It's because wavesurfer.js 7.x is not supported, see #172 I've updated the wavesurfer.js paths (to 6.6.4) in the examples in #175 so this error should be gone there soon.
