### ISSUE TITLE
Node module name for Waveform.js is incorrect

### ISSUE THREAD

**Issue by monachilada** [collab-project/videojs-wavesurfer#18]
## Description
Node module name for Waveform.js is incorrect. Line 13 of videojs.wavesurfer.js should be
`module.exports = factory(require('video.js'), require('wavesurfer.js'));`

## Steps to reproduce
Try to import plugin into my JS

### Expected
That the JS compiles correctly

### Actual
Get an error on compilation that the wavesurfer module can't be found

### Error output
`Cannot find module 'wavesurfer' from 'PATH/node_modules/videojs-wavesurfer'`

**Comment by thijstriemstra** [comment]
Thanks, merged and released (1.2.2).
