### ISSUE TITLE
Controls broken with current video.js and wavesurfer

### ISSUE THREAD

**Issue by Lingomat** [collab-project/videojs-wavesurfer#20]
## Description
Play button doesn't work

## Steps to reproduce
Use the current build of video.js, and wavesurfer 1.1.11. Autoload will play, play controls do not work.

### Expected
Play/pause should work. Calls to player.waveform.play() are ignored.

### Actual
Play/pause does not work. If you use exactly the same version of video.js and wavesurfer, (5.10.8 and 1.1.0) as in the demo, then the control work as described.

### Error output
No errors.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs/wavesurfer
wavesurfer 1.1.11, whatever the current videoJS is.
#### browsers
Chrome
#### OSes
Windows, Android

**Comment by thijstriemstra** [comment]
Thanks for the report @Lingomat, do you see any traceback/errors in the console?

**Comment by Lingomat** [comment]
No, curiously. Downgrading versions and there's a string of errors about pause() interrupting play() but it essentially works. Similarly a call to player.waveform.play() didn't do anything.

**Comment by thijstriemstra** [comment]
@Lingomat I've tried with an older version of video.js (`bower install video.js#5.10.4`) and the latest wavesurfer.js (1.1.12) and the example works again so it seems something changed or broke in video.js. Investigating now.

**Comment by thijstriemstra** [comment]
Looks like this PR broke things: https://github.com/videojs/video.js/pull/3378

**Comment by thijstriemstra** [comment]
@Lingomat I added a fix and tested it against 5.10.x, 5.11.x and also 5.12.0 release candidate. Could you check if it's fixed and I'll add a new release, thanks.

**Comment by thijstriemstra** [comment]
Fixed in v1.2.3 release.
