### ISSUE TITLE
Can i call event onWaveFinish?

### ISSUE THREAD

**Issue by kimhongn89** [collab-project/videojs-wavesurfer#24]
Can you add event waveFinish. Because i want to catch that event for my player

**Comment by thijstriemstra** [comment]
is this a new wavesurfer.js specific event that was recently introduced?

**Comment by thijstriemstra** [comment]
Looks like you want to:

```javascript
player.surfer.on('finish', function() {
    console.log('wave playback finished');
});
```

**Comment by kimhongn89** [comment]
Yes, that is what i need. Have you updated that event :)

**Comment by thijstriemstra** [comment]
@kimhongn89 I'll add a `playbackFinish` event that does the same.

**Comment by thijstriemstra** [comment]
@kimhongn89 I added a `playbackFinish` event, can you try this out? I'll release it in a few days.

**Comment by kimhongn89** [comment]
it worked,
thank you.
