### ISSUE TITLE
Support for video.js fluid option

### ISSUE THREAD

**Issue by Chinese1904** [collab-project/videojs-wavesurfer#28]
Hi everyone,

I am struggling to figure out how to set the height to 100% in order to make it responsive. 

I have tried to set the height via `height: document.getElementById('media').offsetHeight` but it does not work.

Any help would be greatly appreciated!

Chris

**Comment by thijstriemstra** [comment]
@Chinese1904 you should listen for `resize`. Take a look at https://github.com/katspaugh/wavesurfer.js/blob/master/plugin/wavesurfer.minimap.js#L121

**Comment by thijstriemstra** [comment]
In order to have a responsive player, the `fluid` option should be supported, as described here in this blog post: http://blog.videojs.com/Video-js-5-s-fluid-mode-and-playlist-picker/

Use wavesurfer's `debounce` method (available since wavesurfer.js 1.3.1) to make the waveform responsive (https://github.com/katspaugh/wavesurfer.js/pull/964).

**Comment by Chinese1904** [comment]
Fluid usually was my go to, but it does not work with wavesurfer, because it seems that the height needs to be set. I will take a look at debounce :-)

**Comment by thijstriemstra** [comment]
I'm also working on something now, will create a branch with something to test with.

**Comment by Chinese1904** [comment]
Amazing! Looking forward to that!

**Comment by thijstriemstra** [comment]
@Chinese1904 maybe you can checkout and test the `responsive-28` branch. It does scale the player properly (although quite large) but the waveform isn't layered on top of the player anymore, not sure why it floats like that.

**Comment by Chinese1904** [comment]
In the example you still set a height. If I am correct, that height is only for the waves?
The output looks like:
http://i.imgur.com/HPafGQ3.png

**Comment by thijstriemstra** [comment]
Yea the height should still work in my opinion, but ignoring it should use the max height available in the player. Something that still needs to be fixed. Feel free to hack on it and help implement this.

**Comment by Chinese1904** [comment]
If the height is ignored, the waves will be underneath the player and only visible in full screen mode.

**Comment by thijstriemstra** [comment]
It's fixed and available in the `adv-plugin-29` branch (that'll become v2.0.0 eventually).

**Comment by thijstriemstra** [comment]
@Chinese1904 I merged the version 2.0 branch to master and there's now a fluid.html example. Can you checkout git master and see if it works for you?

**Comment by thijstriemstra** [comment]
> I merged the version 2.0 branch to master 

2.0.0 was released just now that includes fluid support.

**Comment by salmanAhmad143** [comment]
HI Team i am struggling an issue while implementing the videojs-wavesurfer. Actaually my requirement is to display the wave along with video togeather. But i didn't find any option into this. Please help me 

Thanks

**Comment by thijstriemstra** [comment]
take a look at the video example @salmanAhmad143: https://collab-project.github.io/videojs-wavesurfer/examples/video.html
