### ISSUE TITLE
videojs Module not found

### ISSUE THREAD

**Issue by zdenham** [collab-project/videojs-wavesurfer#30]
<img width="1079" alt="screen shot 2017-04-16 at 4 51 41 pm" src="https://cloud.githubusercontent.com/assets/16373521/25075256/47af8706-22c5-11e7-8a1c-b3cd986e8634.png">
<img width="457" alt="screen shot 2017-04-16 at 4 52 40 pm" src="https://cloud.githubusercontent.com/assets/16373521/25075257/47b16fbc-22c5-11e7-9416-5979e465127c.png">

Using ES6 and installed through NPM, just ran into this error. Videojs-wavesurfer is looking to resolve a 'videojs' but the official module is video.js. I'll try to fix it with webpack config but should probably be fixed?

**Comment by zdenham** [comment]
```resolve: {
    alias: {
      'videojs': 'video.js'
    }
  }```
Yea pretty quick fix in the config, but I feel that this should be updated, unless I need a 'videojs' module that I don't know about

**Comment by thijstriemstra** [comment]
@zdenham can you point me to the line that shows the video.js project is using 'video.js' as official module?

**Comment by zdenham** [comment]
`/*! videojs-wavesurfer v1.3.2
* https://github.com/collab-project/videojs-wavesurfer
* Copyright (c) Collab 2014-2017 - Licensed MIT */
(function (root, factory)
{
    if (typeof define === 'function' && define.amd)
    {
        // AMD. Register as an anonymous module.
        define(['videojs', 'wavesurfer'], factory);
    }`

line 9: define(['videojs', 'wavesurfer'], factory);

**Comment by thijstriemstra** [comment]
@zdenham in the video.js github repository i mean?

**Comment by zdenham** [comment]
Ohh my bad it says it here: https://www.npmjs.com/package/videojs

**Comment by thijstriemstra** [comment]
That page mentions something about npm, not this issue in particular.

```
This is not the official video.js package. Please use video.js.
```

**Comment by zdenham** [comment]
The issue I was having was that videojs-wavesurfer package was trying to resolve a 'videojs' module. It was not able to find this module and was throwing an error because I didn't have the module installed for the aforementioned reason and videojs-wavesurfer didn't install it automatically.

**Comment by thijstriemstra** [comment]
I understand and I'd like to fix it but I'd also like to have a code reference to the correct value before I change it.

**Comment by iameli** [comment]
The issue is the AMD code's interaction with Webpack. Webpack sees this definition and gets very confused. Should this line not read `video.js` instead of `videojs`? https://github.com/collab-project/videojs-wavesurfer/blob/master/src/js/videojs.wavesurfer.js#L6

**Comment by thijstriemstra** [comment]
I always had issue with `video.js` (didn't work) vs. `videojs` (worked) when using require.js. Since that's been ages and I don't use require.js any longer I'll change it to `video.js` (which is probably also the correct choice and not webpack-specific, although I still can't find any explicit references in the video.js src).
