### ISSUE TITLE
audio quality changes - starts minimal echoing and sound is off

### ISSUE THREAD

**Issue by Chinese1904** [collab-project/videojs-wavesurfer#31]
## Description
I have never noticed this, but a few customers of mine have mentioned that the audio quality changes. When investigating I noticed that the audio seems to be totally off.

## Steps to reproduce
http://clooud.co/media/bad-club-mix-916 play in the browser and then download the file and play in your local player. It is more noticeable starting around 1:00 to 1:12.

When I use the HTML5 audio player or disable wavesurfer the audio plays as desired.

Any ideas on what could cause this?

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs/wavesurfer
videojs 5.19.2 and videojs-wavesurfer's responsive branch.

#### browsers
Chrome 58

#### OSes
macOS

**Comment by thijstriemstra** [comment]
@Chinese1904 are you familiar with ffmpeg? It comes with a tool called `ffprobe` that analyzes the audio file. Can you run `ffprobe` on the audio file and paste the output here?

**Comment by Chinese1904** [comment]
Thanks for the quick response!

Sure it is:

```
ffprobe bad-club-mix-916.mp3
ffprobe version 3.3 Copyright (c) 2007-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libfreetype --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mp3, from 'bad-club-mix-916.mp3':
  Metadata:
    album_artist    : David Guetta & Showtek
    title           : Bad (Club Mix)
    comment         : dirrtyremixes.com / rmxlvrs.com
    genre           : Underground / Club / Progressive
    encoded_by      : masspool djs promo music dj pool
    artist          : David Guetta (and Showtek feat Vassy)
    composer        : `
    album           : Bad - Remixes
    date            : 2014
  Duration: 00:04:31.15, start: 0.025056, bitrate: 321 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
    Metadata:
      encoder         : LAME3.99r
    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 320x320 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

**Comment by thijstriemstra** [comment]
David Guetta! No, I can't help you in that case.

**Comment by thijstriemstra** [comment]
Just kidding, it's MP3. With coverart. Can you convert it to another format, e.g. .wav and see if it still happens?

**Comment by Chinese1904** [comment]
I converted it via `ffmpeg -i bad-club-mix-916.mp3 song.wav` and it started sounding really "bad". Haha

I also tried converting it with `-acodec pcm_u8 -ar 22050` and same result :(

**Comment by thijstriemstra** [comment]
I've tested it on firefox/ubuntu 16.04 and it immediately, from the 1st second, starts playback of 2 tracks on top of eachother. Your JS creates multiple instances is my guess.

**Comment by Chinese1904** [comment]
Wow, sorry for your time. I have been looking at the wrong cause for the longest time. Thank you so much @thijstriemstra !

**Comment by Footprint-Addons** [comment]
I had the same issue. For those who can't follow what is going on:
Instead of using the regular embedding code with sources,:
(function (window, videojs) {
  if (player) {player.dispose()} else {var player}
    var player = window.player = videojs('myPlayer',{
	sources: [{
		src: 'myaudio.mp3', type: 'audio/mp3'
	  }],	
	controls: true,

you have to remove the line with sources:[....] and only indicate the src in the plugins: waversurfer options. Otherwise, the audio file is loaded twice triggering an ever so slight delay between the two which gets worse when you replay the audio or move around in the timeline. Sound may triple or qua-triple that way.
