### ISSUE TITLE
VIDEOJS: ERROR: TypeError: d.default is undefined

### ISSUE THREAD

**Issue by razzbee** [collab-project/videojs-wavesurfer#37]
Hello , I get the error below when trying to use this plugin, I have tried many different versions of videojs but still error persists ..

```
VIDEOJS: ERROR: TypeError: d.default is undefined
Stack trace:
value@http://videotoolbox.app/assets/plugins/videojs/videojs.wavesurfer.min.js:8:3934
r@http://videotoolbox.app/assets/plugins/videojs/video.min.js:2:376
r@http://videotoolbox.app/assets/plugins/videojs/video.min.js:1:7943
U/r.dispatcher@http://videotoolbox.app/assets/plugins/videojs/video.min.js:1:6918
X@http://videotoolbox.app/assets/plugins/videojs/video.min.js:1:7589
trigger@http://videotoolbox.app/assets/plugins/videojs/video.min.js:2:2969
bn</t.prototype.triggerReady/<@http://videotoolbox.app/assets/plugins/videojs/video.min.js:2:7481
r@http://videotoolbox.app/assets/plugins/videojs/video.min.js:2:376
```

**Comment by thijstriemstra** [comment]
@razzbee what version of videojs-wavesurfer? Have you tried the latest v2.0.0? And what browser/operating system?

**Comment by razzbee** [comment]
Yes, using version 2, Firefox 56 on windows

**Comment by thijstriemstra** [comment]
@razzbee can you reproduce this on https://collab-project.github.io/videojs-wavesurfer/examples/index.html? Looks like it's an issue with your minification of javascript.

**Comment by razzbee** [comment]
not sure, I have tried the unminified version but same error

**Comment by thijstriemstra** [comment]
@razzbee not sure? Can you show me some code that reproduces this problem?

**Comment by thijstriemstra** [comment]
@razzbee any news?
