### ISSUE TITLE
Overriding the Html5 tech causes error on videos without plugins

### ISSUE THREAD

**Issue by eiennosihaisya** [collab-project/videojs-wavesurfer#41]
## Description
Can't play video without wavesurfer set up in _plugins_.

## Steps to reproduce
In the video example, change _var player_ to:
```
var player = videojs('myVideo', {
    controls: true,
    autoplay: false,
    fluid: false,
    loop: false,
    width: 600,
    height: 300,
    sources: [{ src: 'media/example.mp4' }]
```
(Remove _plugins_, add _sources_, change _autoplay_)

### Expected
Video to play normally without wavesurfer plugins set up. (I want to have multiple videos on a page, some with wavesurfer, some without)

### Actual
Unresponsive controls on video(s) without wavesurfer set up.

### Error output
Firefox: `_this.activePlayer.activeWavesurferPlugin is undefined`
Chrome:
```
Uncaught TypeError: Cannot read property 'on' of undefined
    at new WavesurferTech (videojs.wavesurfer.js:88)
    at e.loadTech_ (video.min.js:6)
    at e.src_ (video.min.js:6)
    at video.min.js:6
    at $t (video.min.js:1)
    at $t (video.min.js:1)
    at e.<anonymous> (video.min.js:1)
    at r (video.min.js:2)
```

## Additional Information
The problem seems to be with overriding the Html5 tech. Changing line 1082 in videojs.wavesurfer.js from
`_video2.default.registerTech('Html5', _tech2.default);`
to
`_video2.default.registerTech('Wavesurfer', _tech2.default);`
appears to fix this functionality, although videojs.wavesurfer.css is still in effect, which causes the time remaining and fullscreen icon to overlap.

### versions
Using video.js 6.5.1 and wavesurfer.js 2.0.0-beta02 with videojs-wavesurfer 2.0.3 in Firefox Developer Edition 58 and Google Chrome 62 on Windows 10

**Comment by thijstriemstra** [comment]
That sucks, thanks for the report @eiennosihaisya. Any ideas @mfairchild365?

**Comment by mfairchild365** [comment]
Shucks. The main reason for registering the wavesurfer tech as 'Html5' is to prevent vjs from removing the `<audio>` element. See https://github.com/videojs/video.js/blob/master/src/js/player.js#L897 (its hard coded). Removing the audio element removes the text tracks and prevents safari from display the text tracks.

I believe the plugin is initialized before the tech. It might be possible to check whether or not the wavesurfer plugin is initialized from within the tech. If it isn't initialized, do what the original html5 tech would have done instead.

**Comment by thijstriemstra** [comment]
@eiennosihaisya can you try with video.js 6.4.0?

**Comment by eiennosihaisya** [comment]
Trying with video.js 6.4.0 produced the same error.

Looking at the videojs-youtube plugin, it appears videojs has built-in browser detection. (https://github.com/videojs/videojs-youtube/blob/master/dist/Youtube.js#L36)

Perhaps it's possible to only override the Html5 tech if `videojs.browser.IS_SAFARI || videojs.browser.IS_ANY_SAFARI`?

**Comment by thijstriemstra** [comment]
@eiennosihaisya I merged @mfairchild365's PR to master branch, can you check if that fixes the issue for you?

**Comment by eiennosihaisya** [comment]
Yes, the video now plays correctly when the wavesurfer plugin is not initialized. However, it would be desirable to somehow not apply videojs.wavesurfer.css styles in this case, because if playback rates are used, it overlaps the fullscreen button, as can be seen here- https://imgur.com/OsudPUK

**Comment by thijstriemstra** [comment]
@eiennosihaisya the scrollbar doesn't work does it? Why are you showing it?

**Comment by thijstriemstra** [comment]
> Perhaps this could be fixed by including this.player.addClass('videojs-wavesurfer'); (like here) if the plugin is initialized, and then updating the css file with this class?

Sounds good, can you make a pull request?

**Comment by eiennosihaisya** [comment]
> Sounds good, can you make a pull request?
Pull request submitted
