### ISSUE TITLE
Safari playback & rendering issue

### ISSUE THREAD

**Issue by mfairchild365** [collab-project/videojs-wavesurfer#47]
If you pause and then play an audio track in Safari, the waveform canvas will not update (making it look like nothing is happening).

For example, if you play this example and pause it, then try to play it again, the waveform will not update: https://collab-project.github.io/videojs-wavesurfer/examples/texttrack.html

~~I think this is a problem with this plugin because all of the wavesurfer.js examples do not have this issue in safari.~~ (see https://github.com/katspaugh/wavesurfer.js/issues/1215) I've tried to investigate why this is happening, but I can't track it down. Any ideas?

**Comment by thijstriemstra** [comment]
always include the version nrs for everything; browsers, OS, js libs.

**Comment by thijstriemstra** [comment]
I have a feeling it's related to this PR: https://github.com/videojs/video.js/pull/4743/files

**Comment by mfairchild365** [comment]
potentially a duplicate of https://github.com/katspaugh/wavesurfer.js/issues/1215

**Comment by thijstriemstra** [comment]
@mfairchild365 you tried with latest wavesurfer.js 2.0.1?

**Comment by mfairchild365** [comment]
@thijstriemstra Yep, still a problem on 2.0.1.

**Comment by mfairchild365** [comment]
As described in https://github.com/katspaugh/wavesurfer.js/issues/1215#issuecomment-352495059 - forcing the use of the `MediaElement` backend in wavesurfer fixed the issue for me.

**Comment by thijstriemstra** [comment]
This seems related: https://github.com/muaz-khan/RecordRTC/issues/365#issuecomment-352268940

The audio data empty is because `onaudioprocess` is not called on iOS 11.

https://stackoverflow.com/a/46534088/4759808

`Safari on iOS 11 seems to automatically suspend new AudioContext's that aren't created in response to a tap`

**Comment by thijstriemstra** [comment]
Once this issue is resolved we can take a look at texttrack support for Safari.

**Comment by thijstriemstra** [comment]
Also see https://github.com/danielstorey/webrtc-audio-recording

**Comment by thijstriemstra** [comment]
> If you supply your own AudioContext (and createScriptProcessor apparently) that was created in an event handler and pass that to wavesurfer it will hopefully work (in iOS safari and probably also Desktop safari).

I managed to get it to work on Safari (11.1). Creating the audio context and script processor in response to a click or tap and passing them to wavesurfer.js fixed the playback issues we we're seeing. It did require adding a new feature (able to pass script processor) in wavesurfer.js, which I'll add there.

```html
<audio id="myAudio" class="video-js vjs-default-skin"></audio>
<button onclick="startPlayer()">Start player</button>
<script>
var player;

function startPlayer() {
    // Safari 11 automatically suspends new AudioContext's that aren't
    // created in response to a user-gesture, so create on here (inc. the
    // script processor)
    var AudioContext = window.AudioContext || window.webkitAudioContext;
    var context = new AudioContext();
    var processor = context.createScriptProcessor(1024, 1, 1);

    player = videojs('myAudio', {
        controls: true,
        autoplay: false,
        fluid: false,
        loop: false,
        width: 600,
        height: 300,
        plugins: {
            wavesurfer: {
                src: 'media/hal.wav',
                audioContext: context,
                processor: processor,
                msDisplayMax: 10,
                debug: true,
                waveColor: 'grey',
                progressColor: 'black',
                cursorColor: 'black',
                hideScrollbar: true
            }
        }
    }, function(){
        // print version information at startup
        var msg = 'Using video.js '+ videojs.VERSION +
            ' with videojs-wavesurfer ' + videojs.getPluginVersion('wavesurfer');
        videojs.log(msg);
    });

    // error handling
    player.on('error', function(error) {
        console.warn('ERROR:', error);
    });
}
</script>
```

**Comment by thijstriemstra** [comment]
This is also a good post on webkit's autoplay: https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

```javascript
var promise = document.querySelector('video').play();

if (promise !== undefined) {
    promise.catch(error => {
        // Auto-play was prevented
        // Show a UI element to let the user manually start playback
    }).then(() => {
        // Auto-play started
    });
}
```
