### ISSUE TITLE
Video.js version 5 support

### ISSUE THREAD

**Issue by tweed** [collab-project/videojs-wavesurfer#5]
Hi! yep, a terrifically useful plugin - thanks!!

I've been stumbling around looking for a way to have it work with the latest version of wavesurfer and the just released version 5 master branch of videojs.

If anyone could point out how to get running with the new video.js (version 50 which has lots of responsive features now I believe.

**Comment by thijstriemstra** [comment]
Thanks @tweed! At the time of this writing video.js 5.0 has not been released yet. I'm holding off support for that version until it's actually released and called somewhat stable. I'm planning to keep the current version of this plugin compatible with video.js 4.x in a stable branch (1.x.x) and start a 2.0 version on the trunk that is compatible with video.js 5.

Let's keep this ticket open to track video.js 5 progress.

**Comment by tweed** [comment]
Sensational - makes great sense - thanks!

So, I went back to version 4 and understood better that the development branch is now version 5 though stable is of course version 4.
had hoped to see the responsive magic in version 4 though appears, at least for my limited skills, only possible in version 5.

All good !!! looking forward, when you have time of course, to version 2 trunk - woohoo! great to know.

**Comment by paulhovey** [comment]
I tried to use this with videos 5, and got this exception:

TypeError: undefined is not an object (evaluating 'videos.Component.extend')

On line 16:

videojs.Waveform = videojs.Component.extend({

It looks like videojs changed their component system in videojs 5, unfortunately for plugin developers.

**Comment by thijstriemstra** [comment]
Thanks for testing that @paulhovey. I released a new version where npm and bower will limit video.js to v4.x releases only for now.

**Comment by thijstriemstra** [comment]
Here's a list with details about the changes in v5: https://github.com/videojs/video.js/wiki/5.0-Change-Details

**Comment by doublex** [comment]
+1
This excellent plugin should work with v5

**Comment by thijstriemstra** [comment]
progress...

<img width="622" alt="screen shot 2015-10-10 at 02 08 40" src="https://cloud.githubusercontent.com/assets/305679/10408007/e7bd0eda-6ef3-11e5-83cf-73ee16c57968.png">

**Comment by thijstriemstra** [comment]
Well, looks like it wasn't too much work. If you want to help test (@doublex, @tweed, @paulhovey?), check the `videojs5` branch or get the zip: https://github.com/collab-project/videojs-wavesurfer/archive/videojs5.zip. Cheers.

**Comment by paulhovey** [comment]
I tried it and it works!  Awesome!  Thanks for this great plugin!

**Comment by thijstriemstra** [comment]
thanks for testing @paulhovey. About to release 1.0.0! Any issues, please open a new ticket.
