### ISSUE TITLE
Make peaks not ajax only

### ISSUE THREAD

**Issue by vojthor** [collab-project/videojs-wavesurfer#52]
Hi,

would it be possible to make peaks param not ajax only but allow to pass array of peaks instead (as wavesurfer itself allows)?

Thx

**Comment by thijstriemstra** [comment]
@vojthor can you show me an example how you would do this with wavesurfer.js?

**Comment by vojthor** [comment]
Yeah sure,
there is codepen with it for just wavesurfer: https://codepen.io/entonbiba/pen/PmpXqJ

**Comment by thijstriemstra** [comment]
@vojthor I implemented this in #53, can you try it out?

**Comment by thijstriemstra** [comment]
Merged #53 to master.

**Comment by vojthor** [comment]
@thijstriemstra Awesome, works great! Thanks a lot :)

**Comment by thijstriemstra** [comment]
Cool. Released as 2.2.2.
