### ISSUE TITLE
Waveform is not rendering possible due to latency in rendering the DOM

### ISSUE THREAD

**Issue by tobyrisk1** [collab-project/videojs-wavesurfer#54]
## Description
Waveform is not rendering in V2.2.0 and V2.2.2 possible because of latency in rendering the DOM.
On a really simple stripped down version I can get it to work but when used inside my app, the <wave> element fails to be rendered with a height value

Examining the element inspector I can see that wavesurfer is replacing the <audio> object with a <div> and then applying a <wave> element below this, but the <wave> has no height.
After hacking the videojs.wavesurfer.js file .parseOptions function there is a line:

   `var rect = this.player.el_.getBoundingClientRect();`

This seems like it should derive the height of the container. 
The resulting height, width etc.. are all zero unless I insert a time delay of about 700ms. This points towards a latency issue in the container size. 

However, even with this delay the waveform fails to render. I can only think because the waveform is also being derived before the container height is rendered. I just can't find where this is or am I completely barking up the wrong tree.
            
Thanks in advance

## Steps to reproduce
Happens on loading the file.

### Error output
No errors are indicated

### versions
Video.js 6.1.0, wavesurfer 2.0.3, videojs-waversurfer plugin 2.2.0 and 2.2.2
#### browsers
Chrome 65 and Firefox 59.0.1 
#### OSes
Mac OSX,

**Comment by thijstriemstra** [comment]
Without any code to reproduce this, I'm not sure how to help..

**Comment by tobyrisk1** [comment]
Ok thanks, you're right I should check the latest versions first. If I find a way to encapsulate the code that recreates the issue in a way I can share I'll let you know.

**Comment by thijstriemstra** [comment]
@tobyrisk1 what does your player config look like?

**Comment by thijstriemstra** [comment]
@tobyrisk1 there should be an event in the framework you're using that you probably need to wait for. Closing, please re-open if you found a bug.
