### ISSUE TITLE
Show waveform of a big audio file as it loads

### ISSUE THREAD

**Issue by ErezDalet** [collab-project/videojs-wavesurfer#66]
Hi,
I want to show the waveform of a big audio file (at least 100 MB, at least 1 hour).
I can't wait for the whole file to load because it takes a lot of time.
I need to show it right from the start, as it loads.

I know that I can somehow use array of "Pre-recoded Peaks", but it is heavy to receive this data from my server, so I actually can receive arrays of "Pre-recoded Peaks" in chunks, meaning every 1 second I get 10 minutes of the audio as "Pre-recoded Peaks".
But I didn't see a way to concatenate the arrays and update my existing waveform.

Is there a way I can show the waveform as it loads?
(using chunks of "Pre-recoded Peaks" or any other way?)
Thanks!

**Comment by thijstriemstra** [comment]
@ErezDalet try the `backend: 'MediaElement'` wavesurfer.js option.

**Comment by ErezDalet** [comment]
Thanks but this options just allows to hear the audio before the full waveform loads.
It doesn't display it until it is fully loaded.

**Comment by thijstriemstra** [comment]
@ErezDalet you can use the `peaks` option of wavesurfer.js to generate waveform data and pass that to wavesurfer so it can render the waveform instantly.
