### ISSUE TITLE
Graceful recovery from onWaveError?

### ISSUE THREAD

**Issue by nsticco** [collab-project/videojs-wavesurfer#87]
Hello, I am using videojs-wavesurfer 2.9.0 with React 16.8.6. 

My player initially loads inside the componentDidMount lifecycle method of a component. My app has a list of audio files that you can click on, triggering the player component to receive updated props with a new URL. 

Inside a componentDidUpdate lifecycle method, the player is then told to load the URL of the new audio file:

`this.player.wavesurfer().load(selectedURL)`

This all works fine, unless you click through a series of audio URLs very quickly. Then you get two error messages:

`ERROR: fetch error: The user aborted a request.`
`VIDEOJS: ERROR: fetch error: The user aborted a request.`

The last audio URL clicked actually still loads, but the player has now changed color with a dark tint to the background color and the player controls have vanished.

It seems like I can successfully prevent this behavior by going into the onWaveError method of the Wavesurfer class in videojs.wavesurfer.js and disabling:

`this.player.trigger(Event.ERROR, error)`

A couple questions related to this:

1.) Is it ideal behavior for the player to "break" like this when it gets an error that is mostly harmless / recoverable?
2.) Is there a problem in my implementation leading to this or is it normal?

**Comment by thijstriemstra** [comment]
Was able to reproduce this with network throttling enabled in Firefox (2G setting) and this:

```javascript
function start(event) {
    event.target.style.display = 'none';

    var count = 0;
    var url = 'media/Haydn_Adagio.mp3';
    var timer = setInterval(() => {
        count++;
        console.log('load: ' + count);
        this.player.wavesurfer().load(url);
        
        if (count == 2) {
            clearInterval(timer);
        }
    },
    200);
};
```

**Comment by thijstriemstra** [comment]
created a new `abort` event for this (#89) and will release it after wavesurfer 3.1.0 is released.
