### ISSUE TITLE
Can I use wavesurfer with videojs-playlist?

### ISSUE THREAD

**Issue by seabasss** [collab-project/videojs-wavesurfer#91]
Is it possible to use wavesurfer with the [videoplaylist](https://github.com/brightcove/videojs-playlist) plugin? I can't figure out how to merge the two.

Is it possible to attach wavesurfer like this and update the waveform depending on what's playing in the playlist?

```
vidplayer.wavesurfer({
	src: 'can this be fetched from the playlist?',
	msDisplayMax: 10,
	debug: true,
	waveColor: 'grey',
	progressColor: 'black',
	cursorColor: 'black',
	hideScrollbar: true
});
```

I'm getting this error when I'm trying the above approach:
> VIDEOJS: ERROR: TypeError: "this.player.options_.plugins is undefined"

**Comment by thijstriemstra** [comment]
Not yet. But I got it to work in the `v3` branch. Checkout that branch or download it here: https://github.com/collab-project/videojs-wavesurfer/archive/v3.zip and build it using npm. Some help testing would be great @seabasss

**Comment by seabasss** [comment]
@thijstriemstra Thanks! Sorry, I'm a noob when it comes to npm. How do I install a branch? Any chance I can get my hands on a dist folder of 3.0.0? Thanks!

**Comment by thijstriemstra** [comment]
download the zip, unpack and follow instructions here to build the `dist` folder: https://github.com/collab-project/videojs-wavesurfer#development

**Comment by seabasss** [comment]
@thijstriemstra I'm afraid I can't get it to work. I unpack the zip and place the "videojs-wavesurfer-3" folder in the "node_modules" folder and run "npm run build videojs-wavesurfer-3".

It gives me this message: "ENOENT: no such file or directory"

Sorry, first time doing this and I've only installed things using "npm install <package>" before

**Comment by thijstriemstra** [comment]
follow the steps in the link.. you first need to build the dist folder using these steps. unzip, cd unzipped-folder, npm install, npm run build.

**Comment by seabasss** [comment]
@thijstriemstra Cool, I may have gotten it to work. Well, a "videojs.wavesurfer.js" file was generated into a dist folder :) It says version 2.11.0 and not v3 in it, but I'll give it a go. Thanks

**Comment by thijstriemstra** [comment]
ah yea, ill update the version. check the `example/index.html` in the zip for the new settings.

**Comment by seabasss** [comment]
This stuff is way over my head. I've tried for hours, but not getting anywhere :( I see that you moved the src out of the plugins option.

Any way you could get a working example with the following [videojs-playlist](https://github.com/brightcove/videojs-playlist) code?

```
player.playlist([{
  sources: [{
    src: 'http://media.w3.org/2010/05/sintel/trailer.mp4',
    type: 'video/mp4'
  }],
  poster: 'http://media.w3.org/2010/05/sintel/poster.png'
}, {
  sources: [{
    src: 'http://media.w3.org/2010/05/bunny/trailer.mp4',
    type: 'video/mp4'
  }],
  poster: 'http://media.w3.org/2010/05/bunny/poster.png'
}, {
  sources: [{
    src: 'http://vjs.zencdn.net/v/oceans.mp4',
    type: 'video/mp4'
  }],
  poster: 'http://www.videojs.com/img/poster.jpg'
}]);
```
