### ISSUE TITLE
Video.js play/pause toggle broken with wavesurfer MediaElement source

### ISSUE THREAD

**Issue by ybinnenwegin2ip** [collab-project/videojs-wavesurfer#93]
## Description
When using Wavesurfer's MediaElement source via videojs-wavesurfer the play/pause toggle in videojs breaks. The native media controls still work fine, calling the video.js player object's `play()` & `pause()` functions in the console also works.

## Steps to reproduce
Open this jsfiddle:

https://jsfiddle.net/crgdm3vx/

Hit the play icon, nothing happens.

In case the above jsfiddle goes offline:

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Wavesurfer Plugin Video Example</title>

  <link href="https://vjs.zencdn.net/7.6.5/video-js.min.css" rel="stylesheet">
  <link href="https://collab-project.github.io/videojs-wavesurfer/dist/css/videojs.wavesurfer.min.css" rel="stylesheet">

  <script src="https://vjs.zencdn.net/7.6.5/video.min.js"></script>
  <script src="https://unpkg.com/wavesurfer.js"></script>

  <script src="https://collab-project.github.io/videojs-wavesurfer/dist/videojs.wavesurfer.min.js"></script>

  <style>
  /* change player background color */
  #myVideo {
      background-color: #6699FF;
  }
  </style>
</head>
<body>

<video id="myVideo" playsinline class="video-js vjs-default-skin">
  <source src="https://collab-project.github.io/videojs-wavesurfer/examples/media/example.mp4"></source>
</video>

<div id="waveform"></div>

<script>

videoElt = document.querySelector('#myVideo');

var player;
var options = {
    controls: true,
    autoplay: false,
    loop: false,
    width: 600,
    height: 300,
    plugins: {
        wavesurfer: {
            src: videoElt,
            container: '#waveform',
            msDisplayMax: 10,
            debug: true,
            waveColor: '#336699',
            progressColor: 'black',
            cursorColor: 'black',
            hideScrollbar: true,
            // disable options below to hide the video playback,
            // and only show the waveform
            backend: 'MediaElement',
        }
    }
};
  // create player
  player = videojs('myVideo', options, function() {
    // print version information at startup
    var msg = 'Using video.js ' + videojs.VERSION +
        ' with videojs-wavesurfer ' +
        videojs.getPluginVersion('wavesurfer') +
        ' and wavesurfer.js ' + WaveSurfer.VERSION;
    videojs.log(msg);
  });

  player.on('waveReady', function(event) {
    console.log('waveform: ready!');
  });

  player.on('playbackFinish', function(event) {
    console.log('playback finished.');
  });

  // error handling
  player.on('error', function(error) {
    console.warn('ERROR:', error);
  });
</script>

</body>
</html>
```

### Expected
The video should play/pause according to the state of the MediaElement.

### Actual
Nothing.

If debug logging is enabled the "VIDEOJS: Pause playback" & "VIDEOJS: Start playback" messages are written to the javascript console.

### Error output
N.A.

## Versions
Make sure to include the following versions:
### videojs/wavesurfer
video.js: 7.6.5
videojs.wavesurfer: 2.11.0
wavesurfer.js: 3.1.0
### Browsers
Firefox, Chromium
### OSes
Fedora, Arch Linux

**Comment by ybinnenwegin2ip** [comment]
A bit of extra context as to what I'm trying to achieve:

In [this](https://collab-project.github.io/videojs-wavesurfer/examples/video.html) videojs-wavesurfer example the waveform is shown 'in' the video.js window and the video below it. I would like to show the video in the video.js window as it would normally appear and place the waveform in a `div` of my choice.

**Comment by thijstriemstra** [comment]
@ybinnenwegin2ip I'm working on version 3 of this library that will support your use-case. Can you give pull request #94 a try? (make sure to use config in `examples/index.html` config). Please leave any feedback on that pull request.

**Comment by ybinnenwegin2ip** [comment]
@thijstriemstra thanks v3 solves my issue! I've left some (positive) feedback on your pull request. :)

Thanks for your time and have a good day!

**Comment by thijstriemstra** [comment]
thanks! I'll close this once v3.0 is released.
